# basic configuration
markdown: kramdown
permalink: /:categories/:title/

# Change this tracking code with your own tracking code
ga_tracking_code: UA-139717412-2
# Please leave this code here for us to see how Course in a Box get used
p2pu_ga_tracking_code: UA-55722824-1

# Some files we need to exclude, so Github can build the site
exclude: [Gemfile, Gemfile.lock, README.md]

defaults:
  -
    scope:
      path: "" # an empty string here means the home page
    values:
      layout: "home_page"
  -
    scope:
      path: "modules" # an empty string here means all files in the project
    values:
      layout: "course_page"

navbar:
  - title: Learning
    url: /modules/learning/_posts/2023-04-29-info.md
  - title: Resources
    url: /modules/resources/_posts/2023-04-29-info.md
  - title: Bibliography
    url: /modules/bibliography/_posts/2023-05-05-info.md
  - title: Contact
    url: /modules/contact/_posts/2023-04-29-info.md

prose:
  media: img/
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
    - /css

# Set some personal styles and logo for your course
# this is a hex value http://www.w3schools.com/tags/ref_colorpicker.asp
jumbotron_color: "#58D7CB"
jumbotron_image: "img/Kichwa.png"
jumbotron_mask: "img/jumbotron-mask.svg"
jumbotron_icon: 
